### ISSUE TITLE
Stray console.logs when converting to WOFF2

### ISSUE THREAD

**Issue by perry-mitchell** [kekee000/fonteditor-core#29]
When converting _any_ font to `woff2`, I get logs like the following:

```
Compressed 23668 to 12885
Compressed 68786 to 22471.
```

There shouldn't be any logs in my opinion. If there are, they should have some kind of option to turn them off.

I don't see any logs in the codebase, so I'm hoping you might be able to help locate them.

**Comment by kekee000** [comment]
It's woff2 wasm compress log, default set to turn on this log to help debug. 
This will fix in the latest version.
