### ISSUE TITLE
cmap12问题

### ISSUE THREAD

**Issue by csr1618** [kekee000/fonteditor-core#32]
你好，我是用Java代码实现的，cmap12字体我生成了，用你们的编辑器能正确打开和显示，但是打开ttf得时候，提示“不是有效得字体”，我查了一些资料，说cmap12字体中必须包含cmap4。请问，cmap12字体中必须包含cmap4吗？

**Comment by kekee000** [comment]
应该是需要吧，cmap4，字体解析引擎一般都能识别，cmap12旧引擎不一定能认识
