### ISSUE TITLE
glyf2SVG icon content getting lost

### ISSUE THREAD

**Issue by mahesh0431** [kekee000/fonteditor-core#36]
@kekee000 Awesome work you are doing man!!!
I have a question that why the content is getting truncated at the bottom here when I am converting icon from TTF to SVG... The behaviour is the same in the demo app that you have provided as well. Please let me know how to fix it.

![Error Truncated Icon](https://user-images.githubusercontent.com/6804552/91636445-8e3e1b80-ea11-11ea-9577-b780da9cd144.PNG)

Thanks in Advance,
Mahesh

**Comment by kekee000** [comment]
glyphs has baseline, ascent, descent, they  determine bound of  a glyph.
you can scale one glyph  to in bound of a bounding box, or modify ascent and descent in ttfObject to scale all the glyphs.
