### ISSUE TITLE
add cmap format 2 support

### ISSUE THREAD

**Issue by junmer** [kekee000/fonteditor-core#4]
> 'cmap' format 2
The format 2 mapping subtable type is used for fonts containing Japanese, Chinese, or Korean characters. The code standards used in this table are supported on Macintosh systems in Asia. These fonts contain a mixed 8/16-bit encoding, in which certain byte values are set aside to signal the first byte of a 2-byte character. These special values are also legal as the second byte of a 2-byte character.

一些老字体 还是这个格式的，需要兼容一下
中文找不到对应的 unicode

**Comment by kekee000** [comment]
cmap format2 supported， 不过编码不是根据unicode编码来的，没有进行转换，不能直接用于字体，只能用于图标项目
