### ISSUE TITLE
Update to latest version of `xmldom` to patch security vulnerability

### ISSUE THREAD

**Issue by G-Rath** [kekee000/fonteditor-core#44]
[An advisory has been open against `xmldom`](https://www.npmjs.com/advisories/1650) which is used by this library - while the advisory has been patched via `xmldom@0.5.0`, the version constraint here doesn't allow for anything higher than `0.1.x`.

The changelog for `xmldom` can be found [here](https://github.com/xmldom/xmldom/blob/master/CHANGELOG.md).

**Comment by kekee000** [comment]
updated at fonteditor-core@2.1.6
