### ISSUE TITLE
fonteditor-core build error with yarn and laravel-mix

### ISSUE THREAD

**Issue by michaelharrod** [kekee000/fonteditor-core#54]
Hello. I am helping to maintain some code that was set up by someone who has left the organization. I'm having some trouble building the project on a new Windows 11 machine, this seemed to work fine on my previous Windows 10 machine.

I'm running this command.
`yarn mix build`

It gets part way through the build and then raises an error.

![image](https://user-images.githubusercontent.com/8508216/210857151-436d1b1a-9c39-4640-a67a-69d1013a53dc.png)
![image](https://user-images.githubusercontent.com/8508216/210857209-09222fb6-f9d0-4a1f-aa5c-cad687e9f619.png)

It seems to emit the entire contents of woff2.js and encounters some sort of fetch error.

`abort(TypeError: fetch failed) at Error
    at jsStackTrace (C:\Development\MyCompany\Src\Assets\Web\node_modules\fonteditor-core\woff2\woff2.js:8:22389)
    at stackTrace (C:\Development\MyCompany\Src\Assets\Web\node_modules\fonteditor-core\woff2\woff2.js:8:22560)
    at process.abort (C:\Development\MyCompany\Src\Assets\Web\node_modules\fonteditor-core\woff2\woff2.js:8:18310)
    at process.emit (node:events:513:28)
    at emit (node:internal/process/promises:149:20)
    at processPromiseRejections (node:internal/process/promises:283:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
(Use `node --trace-uncaught ...` to show where the exception was thrown)`

I appreciate that this might be specific to my machine and not necessarily a fonteditor-core issue, but I'd really appreciate some guidance on where to go next to get this build working. I don't have a lot of experience with node, yarn, alpine, tailwind etc. but they seem to be part of the technology mix we are now supporting. Thanks!

**Comment by michaelharrod** [comment]
Incidentally, after much Googling and reading GitHub issues, I found it seems to be related to this:
https://github.com/nodejs/undici/issues/1602

In this instance, downgrading to Node v16.19.0 allowed the build to succeed again. I don't consider rolling back to earlier versions to be a permanent fix, but the IPv4 vs IPv6 DNS ordering change in Node v17 seems to have caused so many unresolved headaches that I might stick with this until things stabilise,

**Comment by kekee000** [comment]
woff2.js will not download assets when running.I guess when we use webpack to build project, the analyze scripts cause this problem, ignore woff2.js on build, and use async require this script file.
