### ISSUE TITLE
Does fonteditor-core can handle ttc-files?

### ISSUE THREAD

**Issue by NMarkgraf** [kekee000/fonteditor-core#55]
Dear maintainer,

does fonteditor-core can handle True Type Collection files, a collection of True Type Fonts in on file?

Thanks a lot, yours

Norman

**Comment by kekee000** [comment]
Fonteditor-core can only parse and handle single ttf file.
Ttc has a collection of ttf fonts, we can extract ttc to ttf, and edit ttf, and then combine to ttc.

**Comment by NMarkgraf** [comment]
Well the problem is, in the project "decktape" (https://github.com/astefanutti/decktape) the author uses your grade work. But when it try to read a .ttc file, it gets worse and stop working. On Apple's macOS you can not use ttf-files on system fonts (like "Helvetica Neue"), because they are fixed in non-eraseble ttc-files. :-(

So I am looking for a way to fit their needs. And that might be a fonteditor-core, which can handle ttc-files. ;-)

Thanks for your answer!
Norman
