### ISSUE TITLE
 如何打包成一个文件，供浏览器使用

### ISSUE THREAD

**Issue by orklann** [kekee000/fonteditor-core#6]
请问，这个repo有提供工具，可以打包`src`下面的代码，供浏览器使用吗？(非 `node.js`)

我大概看了一下，`src/main.js` 的代码，发现，如果我为浏览器实现了跟 `node.js` 类似的 `reqiure` 方法，就可以不用打包成一个`js`文件了.

但是，我还最想问的是如何打包成一个`js`文件。

**Comment by asd123freedom** [comment]
可以在本地使用 npm install 安装，然后使用现在前端界流行的 webpack 和 browserify进行打包，这两个打包工具都支持 commonjs 规范。

**Comment by aaron-elkins** [comment]
谢谢啊，终于有了解决办法了，我去试试。
