### ISSUE TITLE
Reliance on `DOMParser` prevents use in Web Workers

### ISSUE THREAD

**Issue by rektdeckard** [kekee000/fonteditor-core#66]
Due to [this check](https://github.com/kekee000/fonteditor-core/blob/9b5e3124490647014f1a9b3faa82546f971b404a/src/common/DOMParser.js#L7), the library throws an error when attempting to use from a Web Worker (`DOMParser` is not available in worker context).

As far as I can tell, DOMParser is only needed to read SVG font inputs. If this feature were made optional, the check could be skipped and the lib would (I presume) function in Web Workers.

**Comment by kekee000** [comment]
Font  support XMLDocument as input, we can define custom svg parser, convert svg to  XMLDocument.
```javascript
import {Font} from 'fonteditor-core';
const doc = new DOMParser().parseFromString(xml, 'text/xml');
const font = Font.create(doc, {type: 'svg'});
// TODO

```

**Comment by rektdeckard** [comment]
I may not have been clear. This library cannot be used in Web Worker contexts because `DOMParser` is not available there. Since the feature is only needed for a narrow use-cases, it would be nice if it was an option to omit it when not needed -- allowing `fonteditor-core` to be used in Workers as long as SVG fonts are not used as inputs or outputs.

**Comment by kekee000** [comment]
fonteditor-core works ok in web worker, if we don't want DOMParser bundled in assets, it's better to do custom bundle, remove xmldom deps.
