### ISSUE TITLE
Using TTFReader with the subset option sometimes returns the wrong glyph for a unicode

### ISSUE THREAD

**Issue by grumpy** [kekee000/fonteditor-core#7]
Using TTFReader with the subset option sometimes returns the wrong glyph for a unicode.

This is most commonly happens with the space character or unicode 0x20, possibly because it is mapped to multiple alternate unicodes.  It doesn't happen with all fonts, but it is quite common.

**Comment by bbqaaq** [comment]
https://github.com/ecomfe/fontmin/issues/68

其實這個問題是沒有解決的
請問一下作者會解決一下?

**Comment by roydukkey** [comment]
@kekee000 Please shed some light on why this was closed? Still seems to be an issue.
