### ISSUE TITLE
Varying md5 hash

### ISSUE THREAD

**Issue by bitbay** [kekee000/fonteditor-core#8]
Got bit by this one the other day - although the inputs do not change, the output is different (as by md5 hash) after each conversion. 

Any option i miss? Is this inevitable?

**Comment by bitbay** [comment]
So digging in the source i found that the "head.modified" is always set to Date.now() in [ttfwriter](https://github.com/kekee000/fonteditor-core/blob/master/src/ttf/ttfwriter.js#L83).
How about a new option to set the modified date to a specific value and/or a boolean to keep the input fonts modified date read from its header?

**Comment by kekee000** [comment]
fixed
