### ISSUE TITLE
OTF not supported in writing

### ISSUE THREAD

**Issue by bjorn-ali-goransson** [kekee000/fonteditor-core#9]

**Comment by bjorn-ali-goransson** [comment]
If you try to write an OTF

     
    var buffer = font.write({
      type: 'otf',
      hinting: true,
    });

... you get the "not support font type" error

But the README says otf is supported:

    var buffer = font.write({
      type: 'woff', // support ttf,woff,eot,otf,svg

**Comment by tybenz** [comment]
Yep I'm seeing this too. Any update on this?

**Comment by sanriqing** [comment]
！！me too
